sudo: false  
language: java
jdk:
  - oraclejdk8    
cache:  
 directories:  
  - $HOME/.m2    
script:
 - cd releng/us.nineworlds.xstreamer.target       
 - ../../mvnw clean install
 - cd ../..
 - ./mvnw clean verify  
